"""Generate requirements.lock: the pinned dependency closure of the project (DX-7).

Walks the installed metadata starting from the project's direct dependencies (runtime + the chroma
and dev extras + the default sentence-transformers embedder), follows Requires-Dist honoring extras
and environment markers, and writes every reachable distribution pinned to its installed version.

Run after changing dependencies, then commit the updated lock:
    python scripts/gen_lock.py
"""

from __future__ import annotations

import importlib.metadata as md
from pathlib import Path

from packaging.requirements import Requirement

LOCK = Path(__file__).resolve().parent.parent / "requirements.lock"

# The full install surface: project runtime deps, the chroma + dev extras, and the default embedder.
ROOTS = [
    "pydantic",
    "pydantic-settings",
    "pyyaml",
    "anthropic",
    "boto3",
    "numpy",
    "langgraph",
    "chromadb",
    "ruff",
    "mypy",
    "pytest",
    "types-PyYAML",
    "sentence-transformers",
]


def _norm(name: str) -> str:
    return name.lower().replace("_", "-")


def closure() -> dict[str, str]:
    """Return {distribution_name: version} for the full reachable dependency set."""
    seen: set[str] = set()
    out: dict[str, str] = {}

    def visit(name: str, extras: tuple[str, ...] = ()) -> None:
        key = _norm(name)
        if key in seen:
            return
        try:
            dist = md.distribution(name)
        except md.PackageNotFoundError:
            return
        seen.add(key)
        out[dist.metadata["Name"]] = dist.version
        for raw in dist.requires or []:
            req = Requirement(raw)
            if req.marker:
                contexts = extras or ("",)
                if not any(req.marker.evaluate({"extra": ex}) for ex in contexts):
                    continue
            visit(req.name, tuple(req.extras))

    for root in ROOTS:
        visit(root)
    return out


def render(pins: dict[str, str]) -> str:
    header = (
        "# Generated by scripts/gen_lock.py. Do not edit by hand.\n"
        "# Pinned dependency closure for a reproducible environment (DX-7).\n"
        "# Regenerate after a dependency change: python scripts/gen_lock.py\n"
    )
    lines = [
        f"{name}=={version}" for name, version in sorted(pins.items(), key=lambda p: p[0].lower())
    ]
    return header + "\n".join(lines) + "\n"


def main() -> None:
    pins = closure()
    LOCK.write_text(render(pins), encoding="utf-8")
    print(f"wrote {LOCK} with {len(pins)} pinned packages")


if __name__ == "__main__":
    main()
